name: deploy-auth-s3

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/auth/**'

defaults:
  run:
    working-directory: packages/auth


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Build
        run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
      - name: Install AWS CLI
        uses: shinyinc/action-aws-cli@v1.2
        # We can use Yandex ObjectStorage with AWS CLI this way
      - name: Sync build folder to Yandex ObjectStorage.
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET_PREFIX }}-container/packages/auth/latest --endpoint-url=https://storage.yandexcloud.net
        env:
          # this is region for Yandex ObjectStorage
          AWS_DEFAULT_REGION: ru-central1
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
